runtime: custom
env: flex

instance_class: F2

network:
  session_affinity: true

automatic_scaling:
  target_cpu_utilization: 0.95
  min_instances: 0
  max_instances: 100
  min_pending_latency: 0ms
  max_pending_latency: 2000ms
  max_concurrent_requests: 20
